### ISSUE TITLE
Drosophila two population msprime simulations slow with recombination map

### ISSUE THREAD

**Issue by tjstruck** [popgensims/stdpopsim#91] opened 2019-06-17 23:58 UTC
I've been trying to add drosophila for the two population analysis, however it seems that incorporating the recombination map into the msprime simulations is slowing it down a lot (ex. I have a simulation with 2 samples per population running and has been running for >5 days).

Is this expected or is there an error on my part? See zipped folder with a standalone script (dmel_two_pop_recomb_example.py) and scripts needed to run snakemake (edited to just run msprime).

[dmel_two_pop_recomb_test.zip](https://github.com/popgensims/stdpopsim/files/3299239/dmel_two_pop_recomb_test.zip)

Let me know if there is any other information that may be useful.

Update:
It took 5 to 6 days for the msprime simulations with two samples per-population to finish.

**Comment by jradrion** [comment] 2019-06-18 19:05
Andy and I have been looking into this, and we think this is standard behavior and not a bug. I had previously used msprime to simulate the same dmel recombination maps under equilibrium for a different project, and I was experiencing run times of ~1hr for simulating a single chromosome (2R) with Ne =2.5e5. The human models take significantly longer to run as well if you bump Ne up > 100,000. It might be worth considering abandoning recombination maps for models with very large Ne, if we will need to do many simulation reps.

**Comment by jeromekelleher** [comment] 2019-06-19 13:05
Having a big Ne really pushes up the effective recombination rate, so it does make simulation times long.

**Comment by jradrion** [comment] 2019-06-24 18:17
I've been running a few tests to check the run times for simulating only chr2R under Li & Stephan (population 0) for samples sizes 2,4,8,16,and 32. Sample sizes 8, 16, and 32 are still running, but since n=2 and n=4 have now finished running, I figured this would be worth sharing.

The run times were 4718 and 8096 minutes, for n=2 and n=4 respectively.

We should probably be thinking about exactly what populations we want to ultimately sample (Africa, Europe, both) and what those samples sizes will be, so that we don't have to simulate more than once. I can then set these up to run on our machine in the Kern lab, and we can just let it go for as long as it takes.

**Comment by jeromekelleher** [comment] 2019-06-24 18:33
Jeez that's slow. Must be a **massive** recombination rate... I wonder how realistic this is, and whether the issues we're talking about in this [preprint](https://www.biorxiv.org/content/10.1101/674440v1) are relevant. Might be worth trying this with a few 1000 generations of DTWF to see what happens? Or is this opening up another can of worms?

**Comment by andrewkern** [comment] 2019-06-24 18:38
what do you think @jeromekelleher - should [this model](https://github.com/popgensims/stdpopsim/blob/19699612a60df578f817e7c44f22c76bbd7a5ad4/stdpopsim/drosophila_melanogaster.py#L151) be feasible and we have a bug somewhere?

**Comment by jeromekelleher** [comment] 2019-06-24 18:58
> what do you think @jeromekelleher - should this model be feasible and we have a bug somewhere?

Looks fine to me. I'm just wondering if all the recombination is actually meaningful - how many ancestors are we getting per generation in the recent past? Might be worth trying with DTWF just to see if there's much difference? Just involves setting ``model="dtwf"`` when calling ``simulate``.

**Comment by andrewkern** [comment] 2019-06-24 19:11
yeah we can give the DTWF a whirl for sure.

**Comment by jeromekelleher** [comment] 2019-06-24 19:17
Worth a go - should speed things up in principle, and be more realistic.

**Comment by jradrion** [comment] 2019-06-24 20:31
Sounds good. I'm on it!

**Comment by jradrion** [comment] 2019-07-08 18:54
Just an update: the DTWF model for Li & Stephan (n=2; chr2R) is still running 14 days later.

**Comment by jradrion** [comment] 2019-07-08 19:02
Runtimes for the other tests are as follows:

chrom | simulation_model | sample_size | demographic_model | time (min) |  
-- | -- | -- | -- | -- | --
2R | dtwf | 2 | LiStephan |  ? |  
2R | standard_coalescent | 2 | LiStephan | 4718 |  
2R | standard_coalescent | 4 | LiStephan | 8096 |  
2R | standard_coalescent | 8 | LiStephan | 10506 |  
2R | standard_coalescent | 16 | LiStephan | 12213 |

**Comment by jeromekelleher** [comment] 2019-07-08 19:24
Thanks @jradrion - looks like that's not a silver bullet then. :disappointed:

**Comment by jradrion** [comment] 2019-07-08 19:26
Unfortunately, no.

**Comment by jradrion** [comment] 2019-08-01 18:41
Update: Hybrid sims don't appear to be any faster in this instance, so I've moved ahead with the genome-wide standard coalescent sims. I'm currently running 10 reps, 50 samples, for both the African and European pops using `LiStephanTwoPopulation`. We have a walltime limit of 30 days; I'm crossing my fingers that they finish in time. I will provide the tree sequences once they have been generated.

**Comment by jradrion** [comment] 2019-09-03 17:06
I have 10 reps of `LiStephanTwoPopulation` simulations for those that would like them. 

[Available here](http://sesame.uoregon.edu/~adkern/dmel_recombination_map/comeron2012_maps.tar.gz)

These are using n = 50, but only simulating a chunk of chr2R (chr2R:10000000-13000000). The whole genome simulations are still running.

**Comment by ckyriazis** [comment] 2019-09-03 22:49
Thanks @jradrion! I will get working on producing preliminary results for the analysis pipeline.

**Comment by jeromekelleher** [comment] 2019-10-03 19:09
I think we can close this --- these sims are slow and that's just how it is I think.

**Closed by jeromekelleher** 2019-10-03 19:09 UTC

**Comment by ckyriazis** [comment] 2019-10-23 20:50
@jradrion any updates on the whole genome simulations?

**Comment by jradrion** [comment] 2019-10-23 22:13
@ckyriazis Yeah, they were recently killed due to cluster maintenance after running for at least 30 days. I think we're going to need to re-scale the population sizes. I'm messaging Andy about this now. I'll get back to you ASAP.

**Comment by ckyriazis** [comment] 2019-10-24 19:18
Ahhh bummer, let me know what he says.
